package com.abatef.fastc2.enums;

public enum ErrorType {
    EXPIRED_JWT,
    INVALID_JWT,
    USED_REFRESH_TOKEN,
    DUPLICATE_KEY,
    VALIDATION_ERROR,
    NON_EXISTING_VALUE,
    NOT_OWNER_OF_PHARMACY,
    NOT_EMPLOYEE_OR_MANAGER
}
